/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select country, count(customer_key) as Total_Customers
from customers 
where country !='n/a'
group by country
order by Total_Customers desc;

-- Find total customers by gender
select gender ,count(customer_key) as Total_customers from customers
group by gender
order by Total_customers desc;

-- Find total products by category
select category ,count(Product_key) as total_Prodcuts from products
group by category
order by total_Prodcuts desc;

-- What is the average costs in each category?
Select category, avg(cost) as Average_cost  from products 
group by category 
order by Average_cost desc;

-- What is the total revenue generated for each category?
Select p.category, sum(s.sales_amount) as Total_revenue  from products as p
join sales as s on p.product_key=s.product_key
group by p.category 
order by Total_revenue desc;

-- What is the total revenue generated by each customer?
select c.customer_key,c.first_name,c.last_name ,sum(s.sales_amount) as total_revenue from sales as s 
join customers as c on c.customer_key=s.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc;

-- What is the distribution of sold items across countries?
select c.country , count(s.order_number) as total_orders_sold from sales as s
join customers as c on c.customer_key=s.customer_key
group by c.country
order by total_orders_sold desc;

